# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : Pygments
encoding: utf-8

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Thaleb's projects
description: "A page for my hobby software"
# keywords: ""
# url: http://nandomoreira.me
# baseurl: "/end2end"
# baseurl: ""

# google_analytics: UA-52446115-1
# repo: http://github.com/nandomoreirame/end2end
# disqus_shortname: "fernandomoreira"
# disqus_site_shortname: "fernandomoreira"

# Author settings
author:
  name      : Karim Tsouli
  job       : Software Engineer
  bio       : "Love to work with old consoles and modernize or mod them."
  thumb     : /images/author.jpg
  email     : karim.tsouli@gmail.com
  #url       : http://nandomoreira.me
  #github    : http://github.com/nandomoreirame
  #twitter   : http://twitter.com/nandomoreirame
  #facebook  : http://facebook.com/fernando.dev
  #linkedin  : http://linkedin.com/in/nandomoreirame

gems: [jekyll-paginate]

# navbar pages
navbar:
  - slug: about
    title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
